# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a1725be6f5b1e54820aed36fc233a1da5ce19baa48b8364dd3e1aaad79223c2c5f9fd7a84e7a330e95a1b82ee100128c99cd3be4b25c4965ce2c4e6796dfaed

test:
  secret_key_base: da53cb8c3df5726fa81072c935c83aa99d6e87989d3717f9b71a71eba51ab1a4e8cebbff178e8a8186109acd55b2247d15d4e1a95eabb6ab675647f712cacf91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
